### ISSUE TITLE
Issues are always 17 :)

### ISSUE THREAD

**Issue by s1lvester** [silsha/infoscreen-v6#11]
Count of issues is always 17.

**Comment by silsha** [comment]
Anscheinend gibt mir die Github-API nicht alle Issues zurück. Dafür habe ich herausgefunden, dass es unter https://api.github.com/repos/raumzeitlabor/rzl-tuwat direkt einen counter für die offenen Issues gibt. Anscheinend aber nicht nicht für die geschlossen, bzw. alle Issues.

Daher erstmal kein Meter mehr auf dem Dashboard, sondern die reine Nummer.
