### ISSUE TITLE
Bildschirmgröße voll ausnutzen

### ISSUE THREAD

**Issue by Cheatha** [silsha/infoscreen-v6#5]
Der neue Infoscreen kann irgendwas über FullHD. Das sollte man auch nutzen, auf meinem Monitor mit 2560x1440 gibt es noch einen großen, schwarzen Rahmen

**Comment by silsha** [comment]
Werde ich anpassen, sobald der Raspberry wieder funktioniert. Entweder haben wir dann mehr Platz für Widgets oder die einzelnen Kacheln werden einfach größer.

**Comment by silsha** [comment]
Ist glaube ich inzwischen gelöst.
