### ISSUE TITLE
Graphen im Hintergrund

### ISSUE THREAD

**Issue by Cheatha** [silsha/infoscreen-v6#8]
Der Verlauf von Daten soll als Graph im Hintergrund transparent dargestellt werden.
![bildschirmfoto 2016-06-13 um 11 35 44](https://cloud.githubusercontent.com/assets/125570/16003030/0536be00-315b-11e6-9795-8fcfc50403ae.png)

**Comment by silsha** [comment]
Eigentlich sollte das bei Temperatur schon der Fall sein. Ist aber anscheinend gerade kaputt. Jedenfalls muss vorher #2 gefixt werden.

**Comment by silsha** [comment]
Wird mit #14 gelöst.
