### ISSUE TITLE
Prozentualer Anteil der Mitglieder an der Bevölkerung

### ISSUE THREAD

**Issue by Don42** [silsha/infoscreen-v6#9]
Das war eine Funktionalität war im alten Infoscreen und fehlt jetzt.

**Comment by s1lvester** [comment]
@Don42 Stand 31.12. hatte Mannheim 317.744 Einwohner. Do the math. :wink:

**Comment by silsha** [comment]
![screen shot 2016-11-08 at 16 37 30](https://cloud.githubusercontent.com/assets/31850/20105411/c861062a-a5d1-11e6-9b4e-80d09ae1ce7f.png)
